In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr=np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [6]:
arr=np.random.rand(0,8,5)
arr

array([], shape=(0, 8, 5), dtype=float64)

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [9]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.random.rand(2,4)

array([[0.77256839, 0.25460596, 0.56190377, 0.16430116],
       [0.32831853, 0.8680145 , 0.83034591, 0.38624829]])

In [16]:
np.random.randn(3,6)

array([[ 3.31150775,  0.17038684,  2.7240693 , -0.28450773, -0.92317439,
         1.08428238],
       [ 0.96827381, -0.24636372,  0.56767916,  0.57045571, -1.42795164,
         0.121342  ],
       [ 0.25485262,  0.38797721,  1.06468014,  0.30311575, -0.45025777,
         0.37935973]])

In [17]:
np.random.randint(0,10,15)

array([8, 7, 6, 0, 6, 8, 7, 4, 0, 0, 0, 6, 4, 8, 3])

In [18]:
np.random.randint(10,100,40)

array([62, 23, 43, 13, 74, 10, 87, 82, 30, 52, 24, 33, 86, 57, 89, 60, 77,
       47, 11, 81, 15, 19, 83, 82, 29, 57, 22, 70, 13, 59, 24, 41, 13, 57,
       12, 88, 85, 14, 26, 11])

In [19]:
import numpy as np

In [20]:
arr=np.arange(2,20)

In [21]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
rand_array=np.random.randint(2,20,15)
rand_array

array([17, 14, 12, 16, 18, 18,  4, 14, 18, 13, 17, 15,  8,  3, 10])

In [23]:
arr.min()

2

In [24]:
rand_array.max()

18

In [25]:
rand_array.argmin()

13

In [26]:
rand_array.argmax()

4

In [27]:
arr=np.eye(6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
arr.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
arr=np.random.rand(2,4)
arr

array([[0.48979408, 0.9434204 , 0.87635793, 0.3644376 ],
       [0.77002756, 0.09068148, 0.11513899, 0.86240552]])

In [30]:
arr.T

array([[0.48979408, 0.77002756],
       [0.9434204 , 0.09068148],
       [0.87635793, 0.11513899],
       [0.3644376 , 0.86240552]])